# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.show_config())

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.1",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directo

c:\Users\profe\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
import numpy as np

# Generate a 2x3x5 3D array with random values between 0 and 1
a = np.random.rand(2, 3, 5)

print("Shape of array:", a.shape)
print("Array contents:")
print(a)
# we can use randint for integers 0-9, random.normal and random.uniform (for uniform distr.)


Shape of array: (2, 3, 5)
Array contents:
[[[0.09557198 0.79310768 0.93557918 0.57307318 0.25629336]
  [0.68344924 0.53168333 0.67600671 0.67053264 0.64873654]
  [0.84927358 0.09257649 0.57888799 0.30294618 0.35397096]]

 [[0.14927951 0.56889115 0.88680246 0.90609826 0.58714559]
  [0.5879652  0.3631162  0.93958251 0.95664142 0.70668174]
  [0.69100118 0.36037598 0.67842179 0.08861906 0.03630556]]]



### 4. Print a.


In [5]:
### [your code here]
print(a)

[[[0.09557198 0.79310768 0.93557918 0.57307318 0.25629336]
  [0.68344924 0.53168333 0.67600671 0.67053264 0.64873654]
  [0.84927358 0.09257649 0.57888799 0.30294618 0.35397096]]

 [[0.14927951 0.56889115 0.88680246 0.90609826 0.58714559]
  [0.5879652  0.3631162  0.93958251 0.95664142 0.70668174]
  [0.69100118 0.36037598 0.67842179 0.08861906 0.03630556]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
### [your code here]
b = np.ones((5, 2, 3))

print("Array 'a' shape:", a.shape)
print("Array 'a' contents:")
print(a)
print("\nArray 'b' shape:", b.shape)
print("Array 'b' contents:")
print(b)

Array 'a' shape: (2, 3, 5)
Array 'a' contents:
[[[0.09557198 0.79310768 0.93557918 0.57307318 0.25629336]
  [0.68344924 0.53168333 0.67600671 0.67053264 0.64873654]
  [0.84927358 0.09257649 0.57888799 0.30294618 0.35397096]]

 [[0.14927951 0.56889115 0.88680246 0.90609826 0.58714559]
  [0.5879652  0.3631162  0.93958251 0.95664142 0.70668174]
  [0.69100118 0.36037598 0.67842179 0.08861906 0.03630556]]]

Array 'b' shape: (5, 2, 3)
Array 'b' contents:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [7]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
### they both have 30 elements and can be checked with size, shape and np.prod(array.shape)



### 8. Are you able to add a and b? Why or why not?


In [9]:
### they can NOT be added because of the shapes which are not compatible a has shape 2,3,5 and b has shape 5,2,3




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
print("\n--- Transposing Array 'b' ---")
c = b.transpose(1, 2, 0)  # re-do dimensions: (5,2,3) -> (2,3,5)
print("Original b shape:", b.shape)
print("Transposed c shape:", c.shape)
print("Array 'a' shape:", a.shape)
print("Do a and c have the same shape?", a.shape == c.shape)
print("\nTransposed array 'c' contents:")
print(c)



--- Transposing Array 'b' ---
Original b shape: (5, 2, 3)
Transposed c shape: (2, 3, 5)
Array 'a' shape: (2, 3, 5)
Do a and c have the same shape? True

Transposed array 'c' contents:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
### it works because a and c have the same shape (2, 3, 5) which also makes the elements compatible, which allows broadcasting - I think
print("\n--- Adding Arrays 'a' and 'c' ---")
d = a + c
print("Addition successful!")
print("Array 'd' shape:", d.shape)
print("Array 'd' contents:")
print(d)



--- Adding Arrays 'a' and 'c' ---
Addition successful!
Array 'd' shape: (2, 3, 5)
Array 'd' contents:
[[[1.09557198 1.79310768 1.93557918 1.57307318 1.25629336]
  [1.68344924 1.53168333 1.67600671 1.67053264 1.64873654]
  [1.84927358 1.09257649 1.57888799 1.30294618 1.35397096]]

 [[1.14927951 1.56889115 1.88680246 1.90609826 1.58714559]
  [1.5879652  1.3631162  1.93958251 1.95664142 1.70668174]
  [1.69100118 1.36037598 1.67842179 1.08861906 1.03630556]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
### [your code here]
print("\n--- Detailed Comparison of Arrays 'a' and 'd' ---")
print("Array 'a' (original random values):")
print(a)
print("\nArray 'd' (a + c, where c contains all 1's):")
print(d)

print("\n--- Deeper Analysis ---")
print("Difference between arrays (d - a):")
difference = d - a
print(difference)

print("\n--- Detailed Explanation ---")
print("• Array 'd' = Array 'a' + 1")
print("• Every element in 'd' is exactly 1 greater than the corresponding element in 'a'")
print("• The difference array contains all 1's, confirming this relationship")



--- Detailed Comparison of Arrays 'a' and 'd' ---
Array 'a' (original random values):
[[[0.09557198 0.79310768 0.93557918 0.57307318 0.25629336]
  [0.68344924 0.53168333 0.67600671 0.67053264 0.64873654]
  [0.84927358 0.09257649 0.57888799 0.30294618 0.35397096]]

 [[0.14927951 0.56889115 0.88680246 0.90609826 0.58714559]
  [0.5879652  0.3631162  0.93958251 0.95664142 0.70668174]
  [0.69100118 0.36037598 0.67842179 0.08861906 0.03630556]]]

Array 'd' (a + c, where c contains all 1's):
[[[1.09557198 1.79310768 1.93557918 1.57307318 1.25629336]
  [1.68344924 1.53168333 1.67600671 1.67053264 1.64873654]
  [1.84927358 1.09257649 1.57888799 1.30294618 1.35397096]]

 [[1.14927951 1.56889115 1.88680246 1.90609826 1.58714559]
  [1.5879652  1.3631162  1.93958251 1.95664142 1.70668174]
  [1.69100118 1.36037598 1.67842179 1.08861906 1.03630556]]]

--- Deeper Analysis ---
Difference between arrays (d - a):
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1


### 12. Multiply a and c. Assign the result to e.


In [15]:
### [your code here]
print("\n--- Multiplying Arrays 'a' and 'c' ---")
e = a * c
print("Multiplication was rockin'!")
print("Array 'e' shape:", e.shape)
print("Array 'e' contents:")
print(e)

print("\n--- Multiplication Analysis ---")
print("Since 'c' contains all 1's:")
print("• e = a * c = a * 1 = a")
print("• Every element in 'e' equals the corresponding element in 'a'")
print("• Multiplying by 1 leaves the original values unchanged")

print("\n--- Let's Verify this stuff ---")
print("Are arrays 'a' and 'e' identical?", np.array_equal(a, e))
print("Difference between 'a' and 'e':")
print(e - a)
print("All differences are zero, confirming e = a")


--- Multiplying Arrays 'a' and 'c' ---
Multiplication was rockin'!
Array 'e' shape: (2, 3, 5)
Array 'e' contents:
[[[0.09557198 0.79310768 0.93557918 0.57307318 0.25629336]
  [0.68344924 0.53168333 0.67600671 0.67053264 0.64873654]
  [0.84927358 0.09257649 0.57888799 0.30294618 0.35397096]]

 [[0.14927951 0.56889115 0.88680246 0.90609826 0.58714559]
  [0.5879652  0.3631162  0.93958251 0.95664142 0.70668174]
  [0.69100118 0.36037598 0.67842179 0.08861906 0.03630556]]]

--- Multiplication Analysis ---
Since 'c' contains all 1's:
• e = a * c = a * 1 = a
• Every element in 'e' equals the corresponding element in 'a'
• Multiplying by 1 leaves the original values unchanged

--- Let's Verify this stuff ---
Are arrays 'a' and 'e' identical? True
Difference between 'a' and 'e':
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
All differences are zero, confirming e = a




### 13. Does e equal to a? Why or why not?


In [17]:
### their values are equal but have different objects and their elements are equal too all = i, j, k





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [19]:
### [your code here]
print("\n--- Statistical Analysis of Array 'd' ---")
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Maximum value in 'd':", d_max)
print("Minimum value in 'd':", d_min)
print("Mean value in 'd':", d_mean)

print("\n--- Assigning Variables ---")
print("d_max =", d_max)
print("d_min =", d_min)
print("d_mean =", d_mean)

print("\n--- tie in to original array 'a' ---")
a_max = np.max(a)
a_min = np.min(a)
a_mean = np.mean(a)

print("Comparison:")
print("a_max =", a_max, "| d_max =", d_max, "| difference =", d_max - a_max)
print("a_min =", a_min, "| d_min =", d_min, "| difference =", d_min - a_min)
print("a_mean =", a_mean, "| d_mean =", d_mean, "| difference =", d_mean - a_mean)

print("\nSince d = a + 1:")
print("• d_max = a_max + 1")
print("• d_min = a_min + 1") 
print("• d_mean = a_mean + 1")




--- Statistical Analysis of Array 'd' ---
Maximum value in 'd': 1.9566414185515715
Minimum value in 'd': 1.036305560074834
Mean value in 'd': 1.5516205550225093

--- Assigning Variables ---
d_max = 1.9566414185515715
d_min = 1.036305560074834
d_mean = 1.5516205550225093

--- tie in to original array 'a' ---
Comparison:
a_max = 0.9566414185515715 | d_max = 1.9566414185515715 | difference = 1.0
a_min = 0.03630556007483399 | d_min = 1.036305560074834 | difference = 1.0
a_mean = 0.5516205550225093 | d_mean = 1.5516205550225093 | difference = 1.0

Since d = a + 1:
• d_max = a_max + 1
• d_min = a_min + 1
• d_mean = a_mean + 1



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [20]:
### [your code here]
import numpy as np

# Given array 'd'
d = np.array([[[1.09557198, 1.79310768, 1.93557918, 1.57307318, 1.25629336],
               [1.68344924, 1.53168333, 1.67600671, 1.67053264, 1.64873654],
               [1.84927358, 1.09257649, 1.57888799, 1.30294618, 1.35397096]],

              [[1.14927951, 1.56889115, 1.88680246, 1.90609826, 1.58714559],
               [1.5879652,  1.3631162,  1.93958251, 1.95664142, 1.70668174],
               [1.69100118, 1.36037598, 1.67842179, 1.08861906, 1.03630556]]])

# Create an empty array 'f' with the same shape as 'd'
f = np.empty((2, 3, 5))

print(f)


[[[1.09557198 1.79310768 1.93557918 1.57307318 1.25629336]
  [1.68344924 1.53168333 1.67600671 1.67053264 1.64873654]
  [1.84927358 1.09257649 1.57888799 1.30294618 1.35397096]]

 [[1.14927951 1.56889115 1.88680246 1.90609826 1.58714559]
  [1.5879652  1.3631162  1.93958251 1.95664142 1.70668174]
  [1.69100118 1.36037598 1.67842179 1.08861906 1.03630556]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [21]:
### [your code here]
import numpy as np

# Given array 'd'
d = np.array([[[1.09557198, 1.79310768, 1.93557918, 1.57307318, 1.25629336],
               [1.68344924, 1.53168333, 1.67600671, 1.67053264, 1.64873654],
               [1.84927358, 1.09257649, 1.57888799, 1.30294618, 1.35397096]],

              [[1.14927951, 1.56889115, 1.88680246, 1.90609826, 1.58714559],
               [1.5879652,  1.3631162,  1.93958251, 1.95664142, 1.70668174],
               [1.69100118, 1.36037598, 1.67842179, 1.08861906, 1.03630556]]])

# Compute d_min and d_mean
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array 'f' with the same shape as 'd'
f = np.empty_like(d)  # Alternatively: np.empty(d.shape)

# Assign 25 where d_min < value < d_mean, else 0 (or leave uninitialized)
f[(d > d_min) & (d < d_mean)] = 25
f[~((d > d_min) & (d < d_mean))] = 0  # Optional: Set other values to 0

print("d_min:", d_min)
print("d_mean:", d_mean)
print("\nResulting array 'f':")
print(f)


d_min: 1.03630556
d_mean: 1.5516205550000002

Resulting array 'f':
[[[25.  0.  0.  0. 25.]
  [ 0. 25.  0.  0.  0.]
  [ 0. 25.  0. 25. 25.]]

 [[25.  0.  0.  0.  0.]
  [ 0. 25.  0.  0.  0.]
  [ 0. 25.  0. 25.  0.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [22]:
### very strange and challenging - unexpected f print


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]